### PR TITLE
26 cmd alias trans

### LINKED ISSUE #26: add new command "gitflow update-translation"
This command will
- Copy all translation from master branch into current branch with confirmation
- git command = "git checkout master -- dirname"
- dir = language folder

Please check all cases
- We have a change in the folder
- We don't have a change in the folder

### PR DESCRIPTION
**Pull request by adhocore**
closes #26 

#### usage
```sh
# set alias
gitflow alias trans -- git checkout master -- language
# also possible: gitflow alias trans "git checkout master -- language"

# use alias
giflow trans
```
---
image
image

### CODE REVIEW

**Comment by z3niths** [comment]
Oh nice, btw how can we store the alias cmd?
node temp folder ? or it will create an ignored config file somewhere

**Comment by adhocore** [comment]
well same as it stores token and sprint/project info

**Comment by z3niths** [comment]
So if I understand correctly we only set the alias once per machine and then we can keep using it right? BTW how can we do the pre-alias from somewhere? For example; we push some config in the project config and gitflow will use the per-project config.

**Comment by adhocore** [comment]
also possible to have per project command via `package.json#gitflow/alias`

**Pull request merged**
